"""Phase 2 exit gate — the contract every downstream module depends on.

Char-offset drift is the most dangerous silent failure in this system: it puts every
highlight slightly off, which looks plausible and survives inspection all the way to a
demo. These are not smoke tests.
"""
import pytest
from sqlalchemy import func, select

from api.app.models import Document, DocumentPage, Dpr, TableCell, TextSpan
from tests.conftest import login

SAMPLE = "samples/dpr_bridge_defective.pdf"


@pytest.fixture(scope="module")
def ingested():
    """Upload and fully ingest the bridge DPR once for the whole module."""
    from fastapi.testclient import TestClient

    from api.app.db import SessionLocal
    from api.app.main import app
    from worker.run import _handlers, run_once

    c = TestClient(app)
    tok = login(c, "applicant@demo.gov.in")["access_token"]
    with open(SAMPLE, "rb") as fh:
        r = c.post("/api/v1/dprs", headers={"Authorization": f"Bearer {tok}"},
                   files={"file": ("bridge.pdf", fh, "application/pdf")},
                   data={"title": "Phase 2 fixture", "self_check": "false"})
    assert r.status_code == 202, r.text
    body = r.json()

    db = SessionLocal()
    if not body.get("duplicate_of_existing_upload"):
        run_once(db, _handlers())
    doc = db.get(Document, body["document_id"])
    yield db, doc
    db.close()


def test_document_reaches_ready(ingested):
    """Asserts the property, not a magic number: the sample is regenerated whenever the
    content generator changes, and pinning an exact page count made a legitimate change to
    the fixtures look like a regression."""
    _, doc = ingested
    assert doc.status == "ready"
    assert doc.page_count >= 300, (
        f"the bridge sample should be a realistic full-scale DPR, got {doc.page_count} pages")


def test_char_offsets_hold_for_every_span(ingested):
    """full_text[char_start:char_end] == text. THE critical identity."""
    db, doc = ingested
    pages = db.scalars(select(DocumentPage)
                       .where(DocumentPage.document_id == doc.id)).all()
    checked = 0
    for page in pages:
        spans = db.scalars(select(TextSpan).where(
            TextSpan.document_id == doc.id,
            TextSpan.page_no == page.page_no)).all()
        for s in spans:
            assert page.full_text[s.char_start:s.char_end] == s.text, (
                f"offset drift on page {page.page_no}")
            checked += 1
    assert checked > 10_000, f"only checked {checked} spans"


def test_every_bbox_is_normalised_and_non_degenerate(ingested):
    db, doc = ingested
    for s in db.scalars(select(TextSpan).where(TextSpan.document_id == doc.id)).all():
        assert len(s.bbox) == 4
        assert all(0.0 <= v <= 1.0 for v in s.bbox), f"bbox out of range: {s.bbox}"
        assert s.bbox[0] <= s.bbox[2] and s.bbox[1] <= s.bbox[3]


def test_pages_are_one_indexed(ingested):
    db, doc = ingested
    lo, hi = db.execute(select(func.min(TextSpan.page_no), func.max(TextSpan.page_no))
                        .where(TextSpan.document_id == doc.id)).one()
    assert lo == 1
    assert hi == doc.page_count


def test_offsets_increase_monotonically_within_a_page(ingested):
    db, doc = ingested
    for page_no in (6, 115, 133, 234):
        spans = db.scalars(select(TextSpan).where(
            TextSpan.document_id == doc.id, TextSpan.page_no == page_no)
            .order_by(TextSpan.char_start)).all()
        starts = [s.char_start for s in spans]
        assert starts == sorted(starts)


def test_table_cells_share_the_text_span_coordinate_space(ingested):
    db, doc = ingested
    cells = db.scalars(select(TableCell).where(TableCell.document_id == doc.id)).all()
    assert cells, "no table cells extracted from the cost abstract"
    for c in cells:
        assert all(0.0 <= v <= 1.0 for v in c.bbox), f"cell bbox out of range: {c.bbox}"


# Page numbers follow the document generated by scripts/make_dpr.py, which is built
# against the KIIFB bridge DPR template. Regenerating the sample can move them; the
# generator prints where each planted item lands.
@pytest.mark.parametrize("needle,page_no", [
    ("Rs. 412.50 crore", 6),      # contradiction anchor 1 — executive summary
    ("418.20", 115),              # contradiction anchor 2 — the stale cost abstract
    ("14.2 per cent", 133),       # the IRR claim chapter 3.9 makes
    ("9,240", 233),               # the inflated bituminous rate, Annexure IV
    ("YEAR-WISE CASH FLOW", 234), # the annexure that disproves the IRR claim
])
def test_planted_defects_are_locatable_with_geometry(ingested, needle, page_no):
    """The real contract: a downstream module can find the text AND get a box to draw."""
    db, doc = ingested
    page = db.scalar(select(DocumentPage).where(
        DocumentPage.document_id == doc.id, DocumentPage.page_no == page_no))
    assert needle in page.full_text, f"{needle!r} not found on page {page_no}"

    idx = page.full_text.index(needle)
    end = idx + len(needle)
    overlapping = db.scalars(select(TextSpan).where(
        TextSpan.document_id == doc.id, TextSpan.page_no == page_no,
        TextSpan.char_start < end, TextSpan.char_end > idx)).all()
    assert overlapping, "no spans overlap the match — nothing to highlight"

    x0 = min(s.bbox[0] for s in overlapping); y0 = min(s.bbox[1] for s in overlapping)
    x1 = max(s.bbox[2] for s in overlapping); y1 = max(s.bbox[3] for s in overlapping)
    assert 0.0 <= x0 < x1 <= 1.0 and 0.0 <= y0 < y1 <= 1.0
    assert (x1 - x0) * (y1 - y0) > 0, "degenerate highlight box"


def test_reingest_is_idempotent(ingested):
    """Invariant #12. A crash + stale-lock reclaim must not double the spans —
    doubled offsets corrupt every highlight in the document, silently."""
    from api.app.models import Job
    from worker import queue
    from worker.tasks.ingest import handle_ingest

    db, doc = ingested
    before = db.query(TextSpan).filter(TextSpan.document_id == doc.id).count()
    assert before > 0

    job = queue.enqueue(db, "ingest", dpr_id=doc.dpr_id, document_id=doc.id)
    # Mark it claimed before running it by hand. Left `queued`, a worker running on the
    # same machine will take it and ingest the SAME document concurrently — which is bug
    # B65 exactly: both clear the derived rows, both re-insert the pages, and one dies on
    # uq_doc_page having already corrupted the other's work. That turned this test into an
    # intermittent failure whose page number moved every run, and it damaged the shared
    # corpus each time.
    job.status, job.locked_by = "running", "test"
    db.commit()
    handle_ingest(db, db.get(Job, job.id))

    after = db.query(TextSpan).filter(TextSpan.document_id == doc.id).count()
    assert after == before, f"re-ingest duplicated spans: {before} -> {after}"


def test_a_page_without_a_text_layer_is_routed_to_ocr():
    """A scan must be reported as unreadable, never treated as a blank page — a silent
    blank becomes a false 'section missing' finding. Built in memory rather than from a
    fixture file so the check does not depend on which samples happen to exist."""
    import io

    import pymupdf
    from PIL import Image, ImageDraw

    from worker.parsers.text import parse_page

    img = Image.new("RGB", (1240, 1754), "white")
    ImageDraw.Draw(img).text((120, 200), "3.7 FINANCIAL ESTIMATES", fill=(20, 20, 20))
    buf = io.BytesIO()
    img.save(buf, format="PNG")

    doc = pymupdf.open()
    page = doc.new_page(width=595, height=842)
    page.insert_image(page.rect, stream=buf.getvalue())
    parsed = parse_page(doc[0], 1)
    doc.close()

    assert parsed.needs_ocr is True, "an image-only page was not routed to OCR"
