/**
 * Plain-English explanations of the CHECK FAMILIES, not of any one document.
 *
 *  This file is documentation of the system's own rule families, written out so an
 *  appraising officer meeting a finding for the first time knows what class of thing it is
 *  and who is expected to act on it. Nothing here is derived from a report, generated by a
 *  model, or specific to a submission — which is exactly why it can be stated with
 *  confidence beside findings that cannot.
 *
 *  It matters most for `data_quality`. A data-quality finding is about OUR reading of the
 *  document, not a defect in the project, and an officer who does not know that will send a
 *  report back to a state agency over a scanning artefact.
 */
export interface CategoryMeta {
  label: string;
  /** What this family of checks is looking for. */
  what: string;
  /** Why an appraisal cares — the sentence an officer can repeat in a note. */
  why: string;
  /** Who is expected to act, which is not always the submitting agency. */
  actor: "applicant" | "ministry" | "system";
}

export const CATEGORY_META: Record<string, CategoryMeta> = {
  completeness: {
    label: "Completeness",
    what: "Whether the report contains a section, figure or annexure the appraisal rubric requires.",
    why: "A missing chapter cannot be appraised at all, so it stalls the file rather than lowering its score. Finding it now saves a round trip.",
    actor: "applicant",
  },
  consistency: {
    label: "Internal consistency",
    what: "Whether two statements inside the same report agree — a figure in a table against the same figure in the narrative, a total against its parts, a date against a schedule.",
    why: "Two different numbers for the same thing means at least one is wrong, and the report itself cannot tell you which. This is the family that most often changes a sanction amount.",
    actor: "applicant",
  },
  financial: {
    label: "Financial sanity",
    what: "Whether the costing adds up and follows the form the rubric expects — totals, contingency, escalation, taxes, phasing.",
    why: "An arithmetic error in an abstract of cost is carried forward into every downstream figure, including the one that is sanctioned.",
    actor: "applicant",
  },
  duplicate: {
    label: "Possible duplication",
    what: "Whether this proposal overlaps a project already sanctioned or already in the pipeline.",
    why: "Overlapping sanctions are found in audit, not in appraisal, and by then the money has moved. This check is cheap and the failure it prevents is not.",
    actor: "ministry",
  },
  geo: {
    label: "Location and coverage",
    what: "Whether the places named in the report are consistent with each other and with the stated coverage.",
    why: "Location errors change who the beneficiaries are, and therefore whether the scheme the report is applying under is the right one.",
    actor: "applicant",
  },
  risk: {
    label: "Delivery risk",
    what: "Signals in the report that are associated with cost or schedule slippage in comparable completed projects.",
    why: "Advisory, and about the class of project rather than about this agency. It is an input to how closely the project is monitored, not a reason to refuse it.",
    actor: "ministry",
  },
  data_quality: {
    label: "Our reading of the document",
    what: "A place where the system could not read the document reliably — an unrecognised scan, a broken table, a page with no text layer.",
    why: "This is a statement about US, not about the project. It does not count against the report, and it must never be the reason a file is returned. It tells you which findings to trust less.",
    actor: "system",
  },
};

export function categoryMeta(key: string): CategoryMeta {
  return CATEGORY_META[key] ?? {
    label: key.replace(/_/g, " "),
    what: "A check run against this report.",
    why: "Advisory.",
    actor: "ministry",
  };
}

export const ACTOR_WORD: Record<CategoryMeta["actor"], string> = {
  applicant: "The submitting organisation can fix this",
  ministry: "For the appraising officer to weigh",
  system: "A limit of our reading, not a defect in the report",
};

/** How a status should be read aloud. Never the word "failed": no evidence in a report is
 *  not proof a requirement was unmet, and the system does not return verdicts. */
export const STATUS_SENTENCE: Record<string, string> = {
  pass: "The report evidences this, and the page is cited.",
  partial: "Something related was found, but it does not fully satisfy the requirement.",
  insufficient_evidence:
    "Nothing in the document could be located either way. This is not a finding that the requirement was unmet.",
  flagged: "Something was found that an officer should look at directly.",
  not_run: "This check was not run for this document — a gap in our coverage, not in the report.",
};

/** The severity scale, said in words. Severity is an ordering of how much attention a
 *  finding deserves, never a ruling. */
export const SEVERITY_SENTENCE: Record<string, string> = {
  critical: "Look at this before the file moves.",
  high: "Worth resolving before sanction.",
  medium: "Worth a question in the appraisal note.",
  low: "Minor — record it and move on.",
  info: "Context, not a defect.",
};
