"""initial schema

Revision ID: 07276e474ffd
Revises: 
Create Date: 2026-08-24 15:50:38.742909
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '001_initial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_code', sa.String(length=60), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('rate_paise', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('cost_index', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organisations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('ministry', 'state_dept', 'implementing_agency', 'consultant', name='org_type'), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('hml_category', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('applicant', 'ministry', name='user_role'), nullable=False),
    sa.Column('can_sanction', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organisation_id'), 'users', ['organisation_id'], unique=False)
    op.create_table('dprs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_name', sa.String(length=500), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('sector_id', sa.UUID(), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('draft', 'processing', 'assessed', 'under_review', 'approved', 'returned', 'rejected', name='dpr_status'), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('is_self_check', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dprs_organisation_id'), 'dprs', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_dprs_sector_id'), 'dprs', ['sector_id'], unique=False)
    op.create_index(op.f('ix_dprs_sha256'), 'dprs', ['sha256'], unique=False)
    op.create_index(op.f('ix_dprs_submitted_by'), 'dprs', ['submitted_by'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dpr_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('completeness_score', sa.Float(), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.Column('cost_realism_score', sa.Float(), nullable=True),
    sa.Column('financial_score', sa.Float(), nullable=True),
    sa.Column('rubric_version', sa.String(length=60), nullable=True),
    sa.Column('engine_version', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dpr_id'], ['dprs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_dpr_id'), 'assessments', ['dpr_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=40), nullable=True),
    sa.Column('dpr_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dpr_id'], ['dprs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_dpr_id'), 'audit_events', ['dpr_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dpr_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('queued', 'parsing', 'ocr', 'indexing', 'ready', 'failed', name='document_status'), nullable=False),
    sa.Column('stage', sa.String(length=60), nullable=True),
    sa.Column('progress', sa.SmallInteger(), nullable=False),
    sa.Column('pages_done', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dpr_id'], ['dprs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_dpr_id'), 'documents', ['dpr_id'], unique=False)
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=False)
    op.create_table('dpr_extractions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dpr_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dpr_id'], ['dprs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dpr_extractions_dpr_id'), 'dpr_extractions', ['dpr_id'], unique=False)
    op.create_table('extracted_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dpr_id', sa.UUID(), nullable=False),
    sa.Column('field_key', sa.String(length=120), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_numeric', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.Enum('regex', 'llm_verified', 'ocr_regex', 'table_cell', 'rule_match', name='extract_method'), nullable=True),
    sa.Column('status', sa.Enum('found', 'not_found', 'not_extracted', 'needs_human_verification', name='field_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dpr_id'], ['dprs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_fields_dpr_id'), 'extracted_fields', ['dpr_id'], unique=False)
    op.create_index('ix_fields_dpr_key', 'extracted_fields', ['dpr_id', 'field_key'], unique=False)
    op.create_table('extraction_rejections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dpr_id', sa.UUID(), nullable=False),
    sa.Column('field_key', sa.String(length=120), nullable=False),
    sa.Column('claimed_value', sa.Text(), nullable=True),
    sa.Column('claimed_span', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(length=60), nullable=False),
    sa.Column('best_fuzzy_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dpr_id'], ['dprs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_rejections_dpr_id'), 'extraction_rejections', ['dpr_id'], unique=False)
    op.create_table('outcome_ranges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dpr_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('peer_count', sa.Integer(), nullable=False),
    sa.Column('peer_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cost_p50', sa.BigInteger(), nullable=True),
    sa.Column('cost_p80', sa.BigInteger(), nullable=True),
    sa.Column('cost_p95', sa.BigInteger(), nullable=True),
    sa.Column('months_p50', sa.Float(), nullable=True),
    sa.Column('months_p80', sa.Float(), nullable=True),
    sa.Column('months_p95', sa.Float(), nullable=True),
    sa.Column('peer_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dpr_id'], ['dprs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcome_ranges_dpr_id'), 'outcome_ranges', ['dpr_id'], unique=False)
    op.create_table('project_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dpr_id', sa.UUID(), nullable=False),
    sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('scope_text', sa.String(length=4000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dpr_id'], ['dprs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_embeddings_dpr_id'), 'project_embeddings', ['dpr_id'], unique=False)
    op.create_table('risk_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dpr_id', sa.UUID(), nullable=False),
    sa.Column('model_version', sa.String(length=120), nullable=False),
    sa.Column('cost_overrun_pct', sa.Float(), nullable=True),
    sa.Column('cost_overrun_ci', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('delay_probability', sa.Float(), nullable=True),
    sa.Column('expected_delay_months', sa.Float(), nullable=True),
    sa.Column('shap_drivers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('features_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dpr_id'], ['dprs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_predictions_dpr_id'), 'risk_predictions', ['dpr_id'], unique=False)
    op.create_table('document_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('width_pt', sa.Float(), nullable=False),
    sa.Column('height_pt', sa.Float(), nullable=False),
    sa.Column('rotation', sa.Integer(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('ocr_used', sa.Boolean(), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('raster_key', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_no', name='uq_doc_page')
    )
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=True),
    sa.Column('dpr_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', 'info', name='finding_severity'), nullable=False),
    sa.Column('category', sa.Enum('completeness', 'consistency', 'cost_realism', 'financial', 'duplicate', 'geo', 'risk', 'data_quality', name='finding_category'), nullable=False),
    sa.Column('status', sa.Enum('pass', 'partial', 'insufficient_evidence', 'flagged', name='finding_status'), nullable=False),
    sa.Column('rule_id', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('match_status', sa.Enum('auto', 'confirmed', 'rejected', name='match_status'), nullable=False),
    sa.Column('score_impact', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dpr_id'], ['dprs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_assessment_id'), 'findings', ['assessment_id'], unique=False)
    op.create_index('ix_findings_dpr', 'findings', ['dpr_id', 'severity'], unique=False)
    op.create_index(op.f('ix_findings_dpr_id'), 'findings', ['dpr_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('noop', 'ingest', 'extract', 'assess', 'predict', name='job_kind'), nullable=False),
    sa.Column('dpr_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='job_status'), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('max_attempts', sa.SmallInteger(), nullable=False),
    sa.Column('locked_by', sa.String(length=120), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dpr_id'], ['dprs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_document_id'), 'jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_jobs_dpr_id'), 'jobs', ['dpr_id'], unique=False)
    op.create_index('ix_jobs_status_created', 'jobs', ['status', 'created_at'], unique=False)
    op.create_table('tables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('bbox', sa.ARRAY(sa.Float(), dimensions=1), nullable=False),
    sa.Column('n_rows', sa.Integer(), nullable=False),
    sa.Column('n_cols', sa.Integer(), nullable=False),
    sa.Column('extractor', sa.String(length=40), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tables_document_id'), 'tables', ['document_id'], unique=False)
    op.create_table('text_spans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('bbox', sa.ARRAY(sa.Float(), dimensions=1), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('font_size', sa.Float(), nullable=True),
    sa.Column('is_bold', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_spans_doc_page', 'text_spans', ['document_id', 'page_no'], unique=False)
    op.create_index(op.f('ix_text_spans_document_id'), 'text_spans', ['document_id'], unique=False)
    op.create_table('finding_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('accepted', 'rejected', 'amended', name='review_decision'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_reviews_finding_id'), 'finding_reviews', ['finding_id'], unique=False)
    op.create_index(op.f('ix_finding_reviews_reviewer_id'), 'finding_reviews', ['reviewer_id'], unique=False)
    op.create_table('table_cells',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('row_idx', sa.Integer(), nullable=False),
    sa.Column('col_idx', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('bbox', sa.ARRAY(sa.Float(), dimensions=1), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cells_table', 'table_cells', ['table_id', 'row_idx', 'col_idx'], unique=False)
    op.create_index(op.f('ix_table_cells_document_id'), 'table_cells', ['document_id'], unique=False)
    op.create_index(op.f('ix_table_cells_table_id'), 'table_cells', ['table_id'], unique=False)
    op.create_table('training_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.String(length=120), nullable=False),
    sa.Column('was_correct', sa.Boolean(), nullable=False),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_feedback_finding_id'), 'training_feedback', ['finding_id'], unique=False)
    # ### end Alembic commands ###



    # ------------------------------------------------------------------
    # audit_events is append-only, enforced HERE rather than in application code.
    # Rules make UPDATE and DELETE silently no-op even for a superuser connection that
    # bypasses grants, so no role — Ministry included — can rewrite the record.
    # A CI test asserts this actually holds; see tests/test_phase1.py.
    # ------------------------------------------------------------------
    op.execute("CREATE RULE audit_events_no_update AS "
               "ON UPDATE TO audit_events DO INSTEAD NOTHING")
    op.execute("CREATE RULE audit_events_no_delete AS "
               "ON DELETE TO audit_events DO INSTEAD NOTHING")


def downgrade() -> None:
    op.execute("DROP RULE IF EXISTS audit_events_no_update ON audit_events")
    op.execute("DROP RULE IF EXISTS audit_events_no_delete ON audit_events")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_feedback_finding_id'), table_name='training_feedback')
    op.drop_table('training_feedback')
    op.drop_index(op.f('ix_table_cells_table_id'), table_name='table_cells')
    op.drop_index(op.f('ix_table_cells_document_id'), table_name='table_cells')
    op.drop_index('ix_cells_table', table_name='table_cells')
    op.drop_table('table_cells')
    op.drop_index(op.f('ix_finding_reviews_reviewer_id'), table_name='finding_reviews')
    op.drop_index(op.f('ix_finding_reviews_finding_id'), table_name='finding_reviews')
    op.drop_table('finding_reviews')
    op.drop_index(op.f('ix_text_spans_document_id'), table_name='text_spans')
    op.drop_index('ix_spans_doc_page', table_name='text_spans')
    op.drop_table('text_spans')
    op.drop_index(op.f('ix_tables_document_id'), table_name='tables')
    op.drop_table('tables')
    op.drop_index('ix_jobs_status_created', table_name='jobs')
    op.drop_index(op.f('ix_jobs_dpr_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_document_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_findings_dpr_id'), table_name='findings')
    op.drop_index('ix_findings_dpr', table_name='findings')
    op.drop_index(op.f('ix_findings_assessment_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_risk_predictions_dpr_id'), table_name='risk_predictions')
    op.drop_table('risk_predictions')
    op.drop_index(op.f('ix_project_embeddings_dpr_id'), table_name='project_embeddings')
    op.drop_table('project_embeddings')
    op.drop_index(op.f('ix_outcome_ranges_dpr_id'), table_name='outcome_ranges')
    op.drop_table('outcome_ranges')
    op.drop_index(op.f('ix_extraction_rejections_dpr_id'), table_name='extraction_rejections')
    op.drop_table('extraction_rejections')
    op.drop_index('ix_fields_dpr_key', table_name='extracted_fields')
    op.drop_index(op.f('ix_extracted_fields_dpr_id'), table_name='extracted_fields')
    op.drop_table('extracted_fields')
    op.drop_index(op.f('ix_dpr_extractions_dpr_id'), table_name='dpr_extractions')
    op.drop_table('dpr_extractions')
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_dpr_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_events_dpr_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_assessments_dpr_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_table('settings')
    op.drop_index(op.f('ix_dprs_submitted_by'), table_name='dprs')
    op.drop_index(op.f('ix_dprs_sha256'), table_name='dprs')
    op.drop_index(op.f('ix_dprs_sector_id'), table_name='dprs')
    op.drop_index(op.f('ix_dprs_organisation_id'), table_name='dprs')
    op.drop_table('dprs')
    op.drop_index(op.f('ix_users_organisation_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sectors')
    op.drop_table('organisations')
    op.drop_table('benchmark_rates')
    # ### end Alembic commands ###
